from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, Optional


# ---------------------------------------------------------------------------
# Import guard
# ---------------------------------------------------------------------------
THIS_DIR = Path(__file__).resolve().parent
if str(THIS_DIR) not in sys.path:
    sys.path.insert(0, str(THIS_DIR))

try:
    import train_core
    from balanced_sampler_patch import install_balanced_batch_sampler
except Exception as exc:
    print("\n[Stage3 FINAL] Import failed.")
    print(f"Current file : {__file__}")
    print(f"Current dir  : {THIS_DIR}")
    print("Expected     : train_core.py and balanced_sampler_patch.py in the same directory.")
    print(f"Original err : {type(exc).__name__}: {exc}")
    raise


# ---------------------------------------------------------------------------
# Install balanced-batch support
# ---------------------------------------------------------------------------
install_balanced_batch_sampler(train_core)


# ---------------------------------------------------------------------------
# Project root and checkpoint selection
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(os.environ.get("FER_PROJECT_ROOT", r"/"))


def _p(*parts: str) -> str:
    return str(Path(*parts))


def resolve_project_path(value: str | None) -> Optional[Path]:
    if value is None or str(value).strip() in {"", "None", "none", "null"}:
        return None
    path = Path(str(value))
    return path if path.is_absolute() else PROJECT_ROOT / path


def choose_existing(candidates: Iterable[Path], *, name: str) -> Path:
    checked = []
    for path in candidates:
        checked.append(str(path))
        if path.exists():
            return path
    raise FileNotFoundError(
        f"No valid {name} found. Checked:\n" + "\n".join(checked)
    )


STAGE2_BEST_CKPT = choose_existing(
    [
        PROJECT_ROOT / "checkpoints" / "best_model_stage2_balanced_clean_0684451_LOCKED.pth",
        PROJECT_ROOT / "checkpoints" / "best_model_stage2_balanced_clean.pth",
        PROJECT_ROOT / "runs" / "training" / "stage2_20260602_110224_seed42" / "checkpoints" / "best_model.pth",
    ],
    name="Stage2 historical-best checkpoint",
)

PSEUDO_STAGE2_FINAL = choose_existing(
    [
        PROJECT_ROOT / "data" / "csv" / "pseudo_labeled_stage2_final.csv",
        PROJECT_ROOT / "data" / "csv" / "pseudo_labeled_stage2.csv",
    ],
    name="final Stage2 pseudo-label CSV",
)


# ---------------------------------------------------------------------------
# Stage3 final config
# ---------------------------------------------------------------------------
# This is not an open-ended experiment. It is the final Stage3 closure run.
#
# Important choices:
# - init from historical best Stage2, not weighted_v2 / clean_v2.
# - use conservative pseudo weight.
# - use balanced batch.
# - do not use class weights together with balanced sampler.
# - unique aliases, do not overwrite Stage2 best.
CONFIG: Dict[str, Any] = {
    # Identity
    "project_root": str(PROJECT_ROOT),
    "stage": "stage3",

    # Data
    "train_csv": _p("data", "csv", "train.csv"),
    "val_csv": _p("data", "csv", "val.csv"),
    "test_csv": _p("data", "csv", "test.csv"),
    "img_base": None,

    # Stage3 pseudo labels generated by Stage2 historical-best teacher.
    "pseudo_csv": str(PSEUDO_STAGE2_FINAL),
    "require_pseudo_conf": True,

    # Start from the best Stage2 checkpoint.
    "init_ckpt": str(STAGE2_BEST_CKPT),

    # Unique final aliases.
    "best_alias_name": "best_model_stage3_final.pth",
    "log_alias_name": "train_stage3_final_log.csv",
    "write_checkpoint_alias": True,
    "alias_overwrite": True,

    # Output layout
    "runs_dir": _p("runs", "training"),
    "checkpoint_alias_dir": _p("checkpoints"),

    # Model
    "model_variant": "large",
    "num_classes": 7,
    "pretrained": False,
    "compile_model": False,
    "strict_checkpoint_load": True,

    # Training
    "device": "cuda",
    "epochs": 120,
    "batch_size": 126,
    "num_workers": 4,
    "pin_memory": True,
    "persistent_workers": True,
    "prefetch_factor": 2,
    "drop_last_train": True,

    # Optimizer
    # Stage3 is a continuation from an already strong checkpoint.
    # Keep LR lower than Stage2.
    "lr": 1e-4,
    "lr_floor": 1e-6,
    "warmup_epochs": 2,
    "weight_decay": 1e-4,

    # Loss
    "label_smoothing": 0.04,
    "use_class_weights": False,
    "class_balance_beta": 0.995,
    "class_weights_from": "labeled_train",

    # Balanced sampler
    "sampling_strategy": "balanced_batch",
    "balanced_per_class": "auto_min",
    "balanced_per_class_source": "labeled_train",
    "balanced_samples_per_class_per_batch": 18,
    "balanced_strict_batch_size": True,
    "balanced_replacement": False,

    # Pseudo-label weighting
    # Conservative: Stage3 should refine, not overwrite the Stage2 model.
    "pseudo_conf_min": 0.0,
    "pseudo_conf_power": 2.0,
    "pseudo_loss_scale": 0.20,
    "pseudo_rampup_epochs": 20,

    # Validation / checkpointing
    "val_interval": 1,
    "early_stop_patience": 20,
    "best_metric": "global_macro_f1",
    "evaluate_test_at_end": True,
    "save_last_every_epoch": True,

    # Reproducibility
    "seed": 42,
    "deterministic_algorithms": False,
    "cudnn_benchmark": False,

    # Stability
    "use_amp": True,
    "grad_clip": True,
    "max_norm": 1.0,

    "run_name": None,

    "notes": (
        "Final Stage3 closure run. Init from historical-best Stage2 balanced clean, "
        "use final Stage2 pseudo labels, conservative pseudo loss, strict balanced batch. "
        "If this does not beat Stage2 historical best, final deliverable remains Stage2."
    ),
}


REQUIRED_FILES = (
    CONFIG["train_csv"],
    CONFIG["val_csv"],
    CONFIG["test_csv"],
    CONFIG["pseudo_csv"],
    CONFIG["init_ckpt"],
)


def preflight() -> None:
    print("\n[Stage3 FINAL] Preflight")
    print(f"PROJECT_ROOT : {PROJECT_ROOT}")
    print(f"STAGE2_CKPT  : {STAGE2_BEST_CKPT}")
    print(f"PSEUDO_CSV   : {PSEUDO_STAGE2_FINAL}")

    missing = []
    for item in REQUIRED_FILES:
        path = resolve_project_path(str(item))
        if path is None or not path.exists():
            missing.append(str(path))
    if missing:
        raise FileNotFoundError(
            "Missing required files:\n" + "\n".join(missing)
        )

    lower_ckpt = str(CONFIG["init_ckpt"]).lower()
    if "weighted" in lower_ckpt or "clean_v2" in lower_ckpt:
        raise ValueError(
            "Stage3 final must not initialize from weighted_v2 / clean_v2 failed checkpoints."
        )

    if CONFIG["use_class_weights"] is not False:
        raise ValueError("Stage3 final uses balanced sampler, so use_class_weights must be False.")

    if CONFIG["batch_size"] != 7 * CONFIG["balanced_samples_per_class_per_batch"]:
        raise ValueError(
            "batch_size must equal 7 * balanced_samples_per_class_per_batch."
        )

    print("\n[Stage3 FINAL] Config audit:")
    for key in [
        "train_csv",
        "val_csv",
        "test_csv",
        "pseudo_csv",
        "init_ckpt",
        "epochs",
        "batch_size",
        "lr",
        "pseudo_loss_scale",
        "pseudo_rampup_epochs",
        "sampling_strategy",
        "balanced_samples_per_class_per_batch",
        "best_alias_name",
        "log_alias_name",
    ]:
        print(f"  {key}: {CONFIG.get(key)!r}")


def run() -> None:
    preflight()
    print("\n[Stage3 FINAL] Starting train_core.main(...)\n")
    train_core.main("stage3", CONFIG)


if __name__ == "__main__":
    run()
